Repository apollographql/apollo-ios, pull requests merged in 2021-06, with the labels that each got.

#1802 Allow different types of fetches on a watcher
  Sources/Apollo/GraphQLQueryWatcher.swift
Labels: 🤏 small-effort

#1847 Networking Cleanup
  Apollo.xcodeproj/project.pbxproj
  Playgrounds/ApolloMacPlayground.playground/Pages/SQLiteCache.xcplaygroundpage/Contents.swift
  Playgrounds/ApolloMacPlayground.playground/Pages/Subscriptions.xcplaygroundpage/Contents.swift
  Sources/Apollo/ApolloClient.swift
  Sources/Apollo/ApolloInterceptor.swift
  Sources/Apollo/AutomaticPersistedQueryInterceptor.swift
  Sources/Apollo/CacheReadInterceptor.swift
  Sources/Apollo/CacheWriteInterceptor.swift
  Sources/Apollo/DefaultInterceptorProvider.swift
  Sources/Apollo/FlexibleDecoder.swift
  Sources/Apollo/GraphQLResponse.swift
  Sources/Apollo/GraphQLResult.swift
  Sources/Apollo/HTTPResponse.swift
  Sources/Apollo/InterceptorProvider.swift
  Sources/Apollo/JSONResponseParsingInterceptor.swift
  Sources/Apollo/LegacyParsingInterceptor.swift
  Sources/Apollo/Parseable.swift
  Sources/Apollo/ResponseCodeInterceptor.swift
  Sources/ApolloCodegenLib/CodeGenerator.swift
  Sources/ApolloCodegenLib/FlexibleDecoder.swift
  Sources/ApolloTestSupport/MockNetworkTransport.swift
  Sources/ApolloWebSocket/ApolloWebSocket.swift
  Sources/ApolloWebSocket/WebSocketTransport.swift
  Tests/ApolloCodegenTests/ASTParsingTests.swift
  Tests/ApolloServerIntegrationTests/DefaultInterceptorProviderIntegrationTests.swift
  Tests/ApolloServerIntegrationTests/StarWarsServerCachingRoundtripTests.swift
  Tests/ApolloServerIntegrationTests/StarWarsSubscriptionTests.swift
  Tests/ApolloServerIntegrationTests/StarWarsWebSocketTests.swift
  Tests/ApolloServerIntegrationTests/TestHelpers/TestConfigs.swift
  Tests/ApolloServerIntegrationTests/UploadTests.swift
  Tests/ApolloTests/AutomaticPersistedQueriesTests.swift
  Tests/ApolloTests/Cache/CacheDependentInterceptorTests.swift
  Tests/ApolloTests/DefaultInterceptorProviderTests.swift
  Tests/ApolloTests/InterceptorTests.swift
  Tests/ApolloTests/RequestChainTests.swift
  Tests/ApolloTests/UploadRequestTests.swift
  Tests/ApolloTests/WebSocket/WebSocketTests.swift
  Tests/ApolloTests/WebSocket/WebSocketTransportTests.swift
Labels: include-in-changelog, 🤏 small-effort

#1848 Pattern matching cache delete
  Sources/Apollo/ApolloStore.swift
  Sources/Apollo/InMemoryNormalizedCache.swift
  Sources/Apollo/NormalizedCache.swift
  Sources/Apollo/RecordSet.swift
  Sources/ApolloSQLite/SQLiteDatabase.swift
  Sources/ApolloSQLite/SQLiteDotSwiftDatabase.swift
  Sources/ApolloSQLite/SQLiteNormalizedCache.swift
  Tests/ApolloTests/BatchedLoadTests.swift
  Tests/ApolloTests/Cache/ReadWriteFromStoreTests.swift
Labels: include-in-changelog
