Repository apollographql/apollo-ios, pull requests merged in 2021-08, with the labels that each got.

#1893 Update subscriptions tutorial to be compatible with recent changes
  docs/source/subscriptions.md
Labels: docs, no-changelog, 2021-08

#1897 Release - 0.46.0
  CHANGELOG.md
  Configuration/Shared/Project-Version.xcconfig
  Playgrounds/ApolloMacPlayground.playground/Pages/Subscriptions.xcplaygroundpage/Contents.swift
  docs/source/api/Apollo/classes/ApolloStore.md
  docs/source/api/Apollo/classes/GraphQLResponse.md
  docs/source/api/ApolloCodegenLib/README.md
  docs/source/api/ApolloCodegenLib/classes/CodeGenerator.md
  docs/source/api/ApolloCodegenLib/classes/EnumGenerator.md
  docs/source/api/ApolloCodegenLib/classes/InputObjectGenerator.md
  docs/source/api/ApolloCodegenLib/classes/InterfaceEnumGenerator.md
  docs/source/api/ApolloCodegenLib/classes/UnionEnumGenerator.md
  docs/source/api/ApolloCodegenLib/enums/ApolloCodegenOptions.CodeGenerationEngine.md
  docs/source/api/ApolloCodegenLib/enums/EnumGenerator.EnumContextKey.md
  docs/source/api/ApolloCodegenLib/enums/EnumGenerator.EnumGenerationError.md
  docs/source/api/ApolloCodegenLib/enums/InflectionRule.md
  docs/source/api/ApolloCodegenLib/enums/InputObjectGenerator.InputObjectEnvironmentKey.md
  docs/source/api/ApolloCodegenLib/enums/InterfaceEnumGenerator.InterfaceEnumContextKey.md
  docs/source/api/ApolloCodegenLib/enums/JSONValue.JSONValueError.md
  docs/source/api/ApolloCodegenLib/enums/JSONValue.md
  docs/source/api/ApolloCodegenLib/enums/UnionEnumGenerator.InterfaceEnumContextKey.md
  docs/source/api/ApolloCodegenLib/extensions/ApolloExtension.md
  docs/source/api/ApolloCodegenLib/extensions/JSONValue.md
  docs/source/api/ApolloCodegenLib/structs/ApolloCodegenOptions.md
  docs/source/api/ApolloCodegenLib/structs/EnumGenerator.SanitizedEnumValue.md
  docs/source/api/ApolloCodegenLib/structs/InputObjectGenerator.SanitizedInputObject.md
  docs/source/api/ApolloCodegenLib/structs/InterfaceEnumGenerator.SanitizedInterfaceObject.md
  docs/source/api/ApolloCodegenLib/structs/SanitizedInputObject.SanitizedInputObjectField.md
  docs/source/api/ApolloCodegenLib/structs/SanitizedInterfaceObject.SanitizedCase.md
  docs/source/api/ApolloCodegenLib/structs/SanitizedUnionObject.SanitizedCase.md
  docs/source/api/ApolloCodegenLib/structs/UnionEnumGenerator.SanitizedUnionObject.md
  docs/source/api/ApolloCodegenLib/typealiases/JSONValue.BooleanLiteralType.md
  docs/source/api/ApolloCodegenLib/typealiases/JSONValue.FloatLiteralType.md
  docs/source/api/ApolloCodegenLib/typealiases/JSONValue.IntegerLiteralType.md
  docs/source/api/ApolloCodegenLib/typealiases/JSONValue.StringLiteralType.md
  docs/source/api/ApolloUtils/extensions/ApolloExtension.md
  docs/source/api/ApolloWebSocket/classes/WebSocketTransport.md
Labels: no-changelog, 2021-08

#1904 Use the provided callback queue instead of the store's default.
  Sources/Apollo/ApolloClient.swift
Labels: include-in-changelog

#1901 Add execution tests for ApolloClient clearCache callback queue
  Apollo.xcodeproj/project.pbxproj
  Sources/Apollo/ApolloStore.swift
  Tests/ApolloTests/ExecutionTests.swift
Labels: no-changelog, 2021-08

#1905 Removes playgrounds from apollo-ios
  Apollo.xcodeproj/project.pbxproj
  Apollo.xcodeproj/xcshareddata/xcschemes/Apollo Playground.xcscheme
  Playgrounds/ApolloCodegenFrontendPlayground.playground/Contents.swift
  Playgrounds/ApolloCodegenFrontendPlayground.playground/contents.xcplayground
  Playgrounds/ApolloMacPlayground.playground/Contents.swift
  Playgrounds/ApolloMacPlayground.playground/Pages/CustomScalars.xcplaygroundpage/Contents.swift
  Playgrounds/ApolloMacPlayground.playground/Pages/Introduction.xcplaygroundpage/Contents.swift
  Playgrounds/ApolloMacPlayground.playground/Pages/Mutations.xcplaygroundpage/Contents.swift
  Playgrounds/ApolloMacPlayground.playground/Pages/Queries.xcplaygroundpage/Contents.swift
  Playgrounds/ApolloMacPlayground.playground/Pages/SQLiteCache.xcplaygroundpage/Contents.swift
  Playgrounds/ApolloMacPlayground.playground/Pages/Subscriptions.xcplaygroundpage/Contents.swift
  Playgrounds/ApolloMacPlayground.playground/contents.xcplayground
  README.md
  RELEASE_CHECKLIST.md
  docs/source/fetching-queries.md
Labels: include-in-changelog, 2021-08

#1908 Update Swift 5.2 package file to remove Starscream from dependency list
  Package@swift-5.2.swift
Labels: include-in-changelog, 2021-08
