Repository apollographql/apollo-ios, pull requests merged in 2021-11, with the labels that each got.

#2009 Create AST for code generation [1/x]
  Apollo.xcodeproj/project.pbxproj
  Sources/AnimalKingdomAPI/Resources.swift
  Sources/ApolloCodegenLib/AST/ASTSelectionSet.swift
  Sources/ApolloCodegenLib/AST/MergedSelectionBuilder.swift
  Sources/ApolloCodegenLib/AST/ScopedSelectionSetHashable.swift
  Sources/ApolloCodegenLib/AST/SelectionSetScope.swift
  Sources/ApolloCodegenLib/AST/SortedSelections.swift
  Sources/ApolloCodegenLib/AST/TypeScopeDescriptor.swift
  Sources/ApolloCodegenLib/Frontend/CompilationResult+SelectionSetMerging.swift
  Sources/ApolloCodegenLib/Frontend/CompilationResult.swift
  Sources/ApolloCodegenLib/Frontend/GraphQLSchema.swift
  Sources/ApolloCodegenLib/Frontend/GraphQLType.swift
  Sources/ApolloCodegenLib/Frontend/JavaScriptBridge.swift
  Sources/ApolloCodegenTestSupport/MockCompilationResult.swift
  Sources/ApolloCodegenTestSupport/MockGraphQLType.swift
  Sources/ApolloUtils/StringInterpolation+NestedIndentation.swift
  Tests/ApolloCodegenTests/AnimalKingdomAPI/AnimalKingdomASTCreationTests.swift
  Tests/ApolloCodegenTests/AnimalKingdomAPI/ExpectedGeneratedOutput/Queries/AllAnimalsQuery.swift
  Tests/ApolloCodegenTests/CodeGenAST/ASTSelectionSetTests.swift
  Tests/ApolloCodegenTests/CodeGenAST/SelectionSetScopeTests.swift
  Tests/ApolloCodegenTests/Frontend/CompilationTests.swift
  Tests/ApolloCodegenTests/Frontend/DocumentParsingAndValidationTests.swift
  Tests/ApolloCodegenTests/TestHelpers/ASTMatchers.swift
Labels: size/large, 2021-10

#2014 Expose `cacheKey` function as `public`
  Sources/Apollo/GraphQLSelectionSet.swift
  Tests/ApolloTests/CacheKeyForFieldTests.swift
Labels: 2021-11

#2028 Update apollo-tooling to v2.33.9
  Sources/ApolloCodegenLib/CLIDownloader.swift
  Sources/ApolloCodegenLib/CLIExtractor.swift
  Sources/StarWarsAPI/API.swift
  Sources/StarWarsAPI/graphql/operationIDs.json
  Tests/ApolloTests/GETTransformerTests.swift
  scripts/run-bundled-codegen.sh
Labels: codegen

#2031 Release `0.50.0`
  CHANGELOG.md
  Configuration/Shared/Project-Version.xcconfig
  docs/source/api/Apollo/structs/GraphQLField.md
  docs/source/api/ApolloCodegenLib/README.md
  docs/source/api/ApolloCodegenLib/enums/ApolloSchemaDownloadConfiguration.DownloadMethod.md
  docs/source/api/ApolloCodegenLib/enums/ApolloSchemaDownloader.SchemaDownloadError.md
  docs/source/api/ApolloCodegenLib/enums/DownloadMethod.HTTPMethod.md
Labels: 2021-11
